// <auto-generated />
namespace GJBCTest.WebApi.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111559320_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
