// <auto-generated />
namespace webERP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class scc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(scc));
        
        string IMigrationMetadata.Id
        {
            get { return "201707200950007_scc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
