// <auto-generated />
namespace webERP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1758 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1758));
        
        string IMigrationMetadata.Id
        {
            get { return "201707200958463_1758"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
