// <auto-generated />
namespace webERP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _07201754 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07201754));
        
        string IMigrationMetadata.Id
        {
            get { return "201707200955020_07201754"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
